project:
  type: website
  output-dir: docs


website:
  title: "Symbiont Abundance Notebook"
  site-url: https://jpglabhome.github.io/SymbID_protbleach/
  repo-url: https://github.com/JPGLABHOME/SymbID_protbleach
  #favicon: /images/favicon.ico
  page-navigation: true

  navbar:
    background: primary
    search: true
    # left:
    #   - text: "What"
    #     file: index.qmd
    #   - text: "Who"  
    #     file: publications.qmd
    #   - text: "How"  
    #     file: posts.qmd
    #  
    right:
      - icon: github
        menu:
          - text: Notebook repo
            url: https://github.com/JPGLABHOME/SymbID_protbleach
            target: _blank
          - text: Lab GitHub
            url:  https://github.com/JPGLABHOME
            target: _blank
      - icon: rss
        href: index.xml
       


    
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    page-layout: full
    code-background: true
    code-copy: true
    code-fold: true

editor: visual